### ISSUE TITLE
No tests available

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-rx#1]
I was looking for tests folder for this plugin to see how it works unfortunately I found none and the documentation can be more detailed to see how the plugin can be used with other `canjs` modules.

**Comment by matthewp** [comment]
@cherifGsoul This package definitely needs some love and someone to "own" it, it's yours if you want it :)

**Comment by cherifGsoul** [comment]
@matthewp ok it makes the opportunity to learn RxJS
